repository: ocp-tests
variants:
 - name: okd
   attributes:
    - _attributes/_okd-attributes.adoc
   build: false
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - whats_new/**/*.adoc
       - installing/**/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster