repository: ocp-tests
variants:
 - name: okd
   attributes:
    - _attributes/_okd-attributes.adoc
   build: false
   files:
     included:
       - architecture/**/*
       - welcome/**/*
       - modules/**/*
       - whats_new/**/*
       - installing/**/*
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster